
dist: trusty

sudo: required

language: python

python:
- 3.6

before_install:
  # Required by Kivy
  # https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2
  - sudo apt-get update
  #- sudo apt-get install python-pip build-essential git python-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev mercurial

# command to install dependencies
install:
  #- pip install hg+http://bitbucket.org/pygame/pygame
  #- pip install --upgrade cython pil --use-mirrors
  #- make
  - pip install -r requirements.txt