
dist: trusty

sudo: required

language: python

python:
- 3.6

before_install:
  # Required by Kivy
  # https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2
  - sudo add-apt-repository ppa:kivy-team/kivy-daily -y
  - sudo apt-get update
  - sudo apt-get install python3-kivy -y


# command to install dependencies
install:

script:
  - python3 tst_basicBallActions.py